/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 *
 * @author agond
 */
public class Sidebar extends javax.swing.JPanel {
    
    /**
     * Creates new form sidebar
     */
    private JFrame mainGUI;
    
    public Sidebar() {
        initComponents();
    }
    
    public Sidebar(JFrame mainGUI) {
        initComponents();
        this.mainGUI = mainGUI;
    }
    
    public void setFocus(String nav_item){
        switch(nav_item){
            case "Statistic":
                btStatistic.setBackground(Color.decode("#01687c"));
                break;
            case "Ticket":
                btTicket.setBackground(Color.decode("#01687c"));
                break;
            case "Promotion":
                btPromotion.setBackground(Color.decode("#01687c"));
                break;
            case "Flight":
                btFlight.setBackground(Color.decode("#01687c"));
                break;
            case "Airline":
                btAirline.setBackground(Color.decode("#01687c"));
                break;
            case "Airport":
                btAirport.setBackground(Color.decode("#01687c"));
                break;
            case "Account":
                btAccount.setBackground(Color.decode("#01687c"));
                break;
            default:
                throw new AssertionError();
        }
    }
    
    public void setPermission(String userRole){
        switch (userRole) {
            case "root":
                
                break;
            case "endUser":
                btStatistic.setVisible(false);
                btAirline.setVisible(false);
                btAirport.setVisible(false);
                btAccount.setVisible(false);
                break;
            case "admin":
                
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNav = new javax.swing.JPanel();
        btTicket = new javax.swing.JButton();
        btStatistic = new javax.swing.JButton();
        btPromotion = new javax.swing.JButton();
        btFlight = new javax.swing.JButton();
        btAirline = new javax.swing.JButton();
        btAirport = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();
        iLogo = new javax.swing.JLabel();
        btSignout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(1, 138, 165));

        pnNav.setBackground(new java.awt.Color(1, 138, 165));

        btTicket.setBackground(new java.awt.Color(1, 138, 165));
        btTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTicket.setForeground(new java.awt.Color(255, 255, 255));
        btTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-ticket-white.png"))); // NOI18N
        btTicket.setText("Vé máy bay");
        btTicket.setBorder(null);
        btTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTicket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTicket.setPreferredSize(new java.awt.Dimension(160, 40));
        btTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTicketActionPerformed(evt);
            }
        });

        btStatistic.setBackground(new java.awt.Color(1, 138, 165));
        btStatistic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btStatistic.setForeground(new java.awt.Color(255, 255, 255));
        btStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-statistic-white.png"))); // NOI18N
        btStatistic.setText("Thống kê");
        btStatistic.setBorder(null);
        btStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btStatistic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btStatistic.setPreferredSize(new java.awt.Dimension(160, 40));
        btStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStatisticActionPerformed(evt);
            }
        });

        btPromotion.setBackground(new java.awt.Color(1, 138, 165));
        btPromotion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btPromotion.setForeground(new java.awt.Color(255, 255, 255));
        btPromotion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-promotion-white.png"))); // NOI18N
        btPromotion.setText("Khuyến mãi");
        btPromotion.setBorder(null);
        btPromotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPromotion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPromotion.setPreferredSize(new java.awt.Dimension(160, 40));
        btPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPromotionActionPerformed(evt);
            }
        });

        btFlight.setBackground(new java.awt.Color(1, 138, 165));
        btFlight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btFlight.setForeground(new java.awt.Color(255, 255, 255));
        btFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-flight-white.png"))); // NOI18N
        btFlight.setText("Chuyến bay");
        btFlight.setBorder(null);
        btFlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFlight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFlight.setPreferredSize(new java.awt.Dimension(160, 40));
        btFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlightActionPerformed(evt);
            }
        });

        btAirline.setBackground(new java.awt.Color(1, 138, 165));
        btAirline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAirline.setForeground(new java.awt.Color(255, 255, 255));
        btAirline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-airline-white.png"))); // NOI18N
        btAirline.setText("Hãng bay");
        btAirline.setBorder(null);
        btAirline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirline.setPreferredSize(new java.awt.Dimension(160, 40));
        btAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAirlineActionPerformed(evt);
            }
        });

        btAirport.setBackground(new java.awt.Color(1, 138, 165));
        btAirport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAirport.setForeground(new java.awt.Color(255, 255, 255));
        btAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-airport-white.png"))); // NOI18N
        btAirport.setText("Sân bay");
        btAirport.setBorder(null);
        btAirport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirport.setPreferredSize(new java.awt.Dimension(160, 40));
        btAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAirportActionPerformed(evt);
            }
        });

        btAccount.setBackground(new java.awt.Color(1, 138, 165));
        btAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAccount.setForeground(new java.awt.Color(255, 255, 255));
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-account-white.png"))); // NOI18N
        btAccount.setText("Tài khoản");
        btAccount.setBorder(null);
        btAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAccount.setPreferredSize(new java.awt.Dimension(160, 40));
        btAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNavLayout = new javax.swing.GroupLayout(pnNav);
        pnNav.setLayout(pnNavLayout);
        pnNavLayout.setHorizontalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnNavLayout.setVerticalGroup(
            pnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavLayout.createSequentialGroup()
                .addComponent(btStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 113, Short.MAX_VALUE))
        );

        iLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        iLogo.setMaximumSize(new java.awt.Dimension(116, 31));
        iLogo.setMinimumSize(new java.awt.Dimension(116, 31));
        iLogo.setPreferredSize(new java.awt.Dimension(160, 62));

        btSignout.setBackground(new java.awt.Color(1, 138, 165));
        btSignout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSignout.setForeground(new java.awt.Color(255, 255, 255));
        btSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/logout-white.png"))); // NOI18N
        btSignout.setText("Đăng xuất");
        btSignout.setBorder(null);
        btSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSignout.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btSignout.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btSignout.setPreferredSize(new java.awt.Dimension(160, 40));
        btSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSignout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btSignout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTicketActionPerformed

    private void btStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStatisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStatisticActionPerformed

    private void btPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPromotionActionPerformed

    private void btFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFlightActionPerformed

    private void btAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAirlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAirlineActionPerformed

    private void btAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAirportActionPerformed

    private void btAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAccountActionPerformed

    private void btSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignoutActionPerformed
        mainGUI.dispose();
        SigninGUI signinGUI = null;
        try {
            signinGUI = new SigninGUI();
        } catch (SQLException ex) {
            Logger.getLogger(Sidebar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Sidebar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Sidebar.class.getName()).log(Level.SEVERE, null, ex);
        }
        signinGUI.showWindow();
    }//GEN-LAST:event_btSignoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btAirline;
    private javax.swing.JButton btAirport;
    private javax.swing.JButton btFlight;
    private javax.swing.JButton btPromotion;
    private javax.swing.JButton btSignout;
    private javax.swing.JButton btStatistic;
    private javax.swing.JButton btTicket;
    private javax.swing.JLabel iLogo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnNav;
    // End of variables declaration//GEN-END:variables
}
