/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;

import assets.Styles;

/**
 *
 * @author agond
 */
public class PopupHeader extends javax.swing.JPanel {

    /**
     * Creates new form PopupHeader
     */
    public PopupHeader() {
        initComponents();
        style();
    }
    
    public PopupHeader(String header, String iconURL) {
        initComponents();
        lbHeader.setText(header);
        try {
            lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconURL)));
        } catch (java.lang.NullPointerException e) {
            lbHeader.setIcon(null);
        }        
        style();
    }
    
    public void style(){
        Styles.PopupHeader(lbHeader);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHeader = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 138, 165));

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-user-white32.png"))); // NOI18N
        lbHeader.setText("Header");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(lbHeader)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbHeader)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHeader;
    // End of variables declaration//GEN-END:variables
}
