/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;

import GUI.IndexAD;
import assets.Site.Order ;
import javax.swing.BorderFactory;

import assets.Styles;
import javax.swing.JFrame;

/**
 *
 * @author agond
 */
public class SidebarAD extends javax.swing.JPanel implements iSidebar{
    Order siteOrder;
    JFrame frParrent;
    /**
     * Creates new form SidebarEUC
     */
    public SidebarAD() {
        initComponents();
        style();
    }
    
    public SidebarAD(JFrame frParrent) {
        initComponents();
        style();
        siteOrder = Order.STATISTIC;
        siteOrder(siteOrder);
        this.frParrent = frParrent;
    }
    
    @Override
    public void style(){
        this.setBackground(Styles.PRI_NORMAL);

        btStatistic.setBorder(BorderFactory.createEmptyBorder());
        btStatistic.setFont(Styles.Label);
        btStatistic.setForeground(Styles.WHITE);

        btTicket.setBorder(BorderFactory.createEmptyBorder());
        btTicket.setFont(Styles.Label);
        btTicket.setForeground(Styles.WHITE);

        btPromo.setBorder(BorderFactory.createEmptyBorder());
        btPromo.setFont(Styles.Label);
        btPromo.setForeground(Styles.WHITE);

        btFlight.setBorder(BorderFactory.createEmptyBorder());
        btFlight.setFont(Styles.Label);
        btFlight.setForeground(Styles.WHITE);

        btAirline.setBorder(BorderFactory.createEmptyBorder());
        btAirline.setFont(Styles.Label);
        btAirline.setForeground(Styles.WHITE);

        btAirport.setBorder(BorderFactory.createEmptyBorder());
        btAirport.setFont(Styles.Label);
        btAirport.setForeground(Styles.WHITE);

        btAccount.setBorder(BorderFactory.createEmptyBorder());
        btAccount.setFont(Styles.Label);
        btAccount.setForeground(Styles.WHITE);

        btLogout.setBorder(BorderFactory.createEmptyBorder());
        btLogout.setFont(Styles.Label);
        btLogout.setForeground(Styles.WHITE);
    }
    
    @Override
    public void resetNavItemBG(){
        btStatistic.setBackground(this.getBackground());
        btTicket.setBackground(this.getBackground());
        btPromo.setBackground(this.getBackground());
        btFlight.setBackground(this.getBackground());
        btAirline.setBackground(this.getBackground());
        btAirport.setBackground(this.getBackground());
        btAccount.setBackground(this.getBackground());
    }
    
    @Override
    public void siteOrder(Order siteOrder){
        this.siteOrder = siteOrder;
        style();        
        if(siteOrder == Order.STATISTIC){
            resetNavItemBG();
            btStatistic.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.TICKET) {
            resetNavItemBG();
            btTicket.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.PROMOTION) {
            resetNavItemBG();
            btPromo.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.FLIGHT) {
            resetNavItemBG();
            btFlight.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.AIRLINE) {
            resetNavItemBG();
            btAirline.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.AIRPORT) {
            resetNavItemBG();
            btAirport.setBackground(Styles.PRI_DARK);
        } else if (siteOrder == Order.ACCOUNT) {
            resetNavItemBG();
            btAccount.setBackground(Styles.PRI_DARK);
        }
    }
    
    @Override
    public void navigateTo(Order siteOrder){
        ((IndexAD)frParrent).SiteOrder(siteOrder);
        this.siteOrder(siteOrder);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpNav = new javax.swing.ButtonGroup();
        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btStatistic = new javax.swing.JButton();
        btTicket = new javax.swing.JButton();
        btPromo = new javax.swing.JButton();
        btFlight = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btAirline = new javax.swing.JButton();
        btAirport = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 138, 165));
        setPreferredSize(new java.awt.Dimension(200, 600));

        pnHeader.setBackground(getBackground());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/log-header-logo.png"))); // NOI18N

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btStatistic.setBackground(getBackground());
        btStatistic.setForeground(new java.awt.Color(255, 255, 255));
        btStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-statistic-white20.png"))); // NOI18N
        btStatistic.setText("Thống kê");
        btStatistic.setBorder(null);
        grpNav.add(btStatistic);
        btStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btStatistic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btStatistic.setIconTextGap(12);
        btStatistic.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btTicket.setBackground(getBackground());
        btTicket.setForeground(new java.awt.Color(255, 255, 255));
        btTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-ticket-white20.png"))); // NOI18N
        btTicket.setText("Vé máy bay");
        btTicket.setBorder(null);
        grpNav.add(btTicket);
        btTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTicket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTicket.setIconTextGap(12);
        btTicket.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btPromo.setBackground(getBackground());
        btPromo.setForeground(new java.awt.Color(255, 255, 255));
        btPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-promotion-white20.png"))); // NOI18N
        btPromo.setText("Khuyến mãi");
        btPromo.setBorder(null);
        grpNav.add(btPromo);
        btPromo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPromo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPromo.setIconTextGap(12);
        btPromo.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btFlight.setBackground(getBackground());
        btFlight.setForeground(new java.awt.Color(255, 255, 255));
        btFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-flight-white20.png"))); // NOI18N
        btFlight.setText("Chuyến bay");
        btFlight.setBorder(null);
        grpNav.add(btFlight);
        btFlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFlight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFlight.setIconTextGap(12);
        btFlight.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btLogout.setBackground(getBackground());
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-logout-white20.png"))); // NOI18N
        btLogout.setText("Đăng xuất");
        btLogout.setBorder(null);
        grpNav.add(btLogout);
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLogout.setIconTextGap(12);
        btLogout.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btAirline.setBackground(getBackground());
        btAirline.setForeground(new java.awt.Color(255, 255, 255));
        btAirline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-airline-white20.png"))); // NOI18N
        btAirline.setText("Hãng bay");
        btAirline.setBorder(null);
        grpNav.add(btAirline);
        btAirline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirline.setIconTextGap(12);
        btAirline.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btAirport.setBackground(getBackground());
        btAirport.setForeground(new java.awt.Color(255, 255, 255));
        btAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-airport-white20.png"))); // NOI18N
        btAirport.setText("Sân bay");
        btAirport.setBorder(null);
        grpNav.add(btAirport);
        btAirport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirport.setIconTextGap(12);
        btAirport.setMargin(new java.awt.Insets(2, 16, 2, 16));

        btAccount.setBackground(getBackground());
        btAccount.setForeground(new java.awt.Color(255, 255, 255));
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-account-white20.png"))); // NOI18N
        btAccount.setText("Tài khoản");
        btAccount.setBorder(null);
        grpNav.add(btAccount);
        btAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAccount.setIconTextGap(12);
        btAccount.setMargin(new java.awt.Insets(2, 16, 2, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(btStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btPromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btFlight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        frParrent.setVisible(false);
    }//GEN-LAST:event_btLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btAirline;
    private javax.swing.JButton btAirport;
    private javax.swing.JButton btFlight;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btPromo;
    private javax.swing.JButton btStatistic;
    private javax.swing.JButton btTicket;
    private javax.swing.ButtonGroup grpNav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnHeader;
    // End of variables declaration//GEN-END:variables

}
