/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;

import GUI.IndexAD;
import GUI.SigninGUI;
import GUI.SignupEUC;
import assets.Site.Order ;
import assets.Styles;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author agond
 */
public class SidebarAD extends javax.swing.JPanel implements ISidebar{
    Order siteOrder;
    JFrame context;
    /**
     * Creates new form SidebarEUC
     */
    public SidebarAD() {
        initComponents();
        style();
        siteOrder = Order.STATISTIC;
        siteOrder(siteOrder);
    }
    
    public SidebarAD(JFrame context) {
        initComponents();
        style();
        siteOrder = Order.STATISTIC;
        siteOrder(siteOrder);
        this.context = context;
    }
    
    @Override
    public void style(){
        this.setBackground(Styles.PRI_NORMAL);
        Styles.SidebarNavItem(btStatistic);
        Styles.SidebarNavItem(btTicket);
        Styles.SidebarNavItem(btPromo);
        Styles.SidebarNavItem(btFlight);
        Styles.SidebarNavItem(btAirline);
        Styles.SidebarNavItem(btAirport);
        Styles.SidebarNavItem(btAccount);
        Styles.SidebarNavItem(btLogout);
        Styles.SidebarNavItem(btFeatures);
    }
    
    @Override
    public void resetNavItemBG(){
        btStatistic.setBackground(this.getBackground());
        btTicket.setBackground(this.getBackground());
        btPromo.setBackground(this.getBackground());
        btFlight.setBackground(this.getBackground());
        btAirline.setBackground(this.getBackground());
        btAirport.setBackground(this.getBackground());
        btAccount.setBackground(this.getBackground());
        btFeatures.setBackground(this.getBackground());
    }
    
    @Override
    public void siteOrder(Order siteOrder){
        this.siteOrder = siteOrder;
        style();                
        resetNavItemBG();
        switch (siteOrder) {
            case STATISTIC:
                btStatistic.setBackground(Styles.PRI_DARK);
                break;
            case TICKET:
                btTicket.setBackground(Styles.PRI_DARK);
                break;
            case PROMOTION:
                btPromo.setBackground(Styles.PRI_DARK);
                break;
            case FLIGHT:
                btFlight.setBackground(Styles.PRI_DARK);
                break;
            case AIRLINE:
                btAirline.setBackground(Styles.PRI_DARK);
                break;
            case AIRLINEPLANE:
                break;
            case AIRPORT:
                btAirport.setBackground(Styles.PRI_DARK);
                break;
            case ACCOUNT:
                btAccount.setBackground(Styles.PRI_DARK);
                break;
            case FEATURES:
                btFeatures.setBackground(Styles.PRI_DARK);
                break;
            default:
                throw new AssertionError();
        }
    }
    
    @Override
    public void navigateTo(Order siteOrder) throws ClassNotFoundException, SQLException, IOException{
        ((IndexAD)context).SiteOrder(siteOrder);
        this.siteOrder(siteOrder);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpNav = new javax.swing.ButtonGroup();
        pnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btStatistic = new javax.swing.JButton();
        btTicket = new javax.swing.JButton();
        btPromo = new javax.swing.JButton();
        btFlight = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btAirline = new javax.swing.JButton();
        btAirport = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();
        btFeatures = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 138, 165));
        setPreferredSize(new java.awt.Dimension(200, 600));

        pnHeader.setBackground(getBackground());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/log-header-logo.png"))); // NOI18N

        jSeparator1.setBackground(Styles.PRI_DARK);
        jSeparator1.setForeground(Styles.PRI_DARK);

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btStatistic.setBackground(getBackground());
        btStatistic.setForeground(new java.awt.Color(255, 255, 255));
        btStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-statistic-white20.png"))); // NOI18N
        btStatistic.setText("Thống kê");
        btStatistic.setBorder(null);
        grpNav.add(btStatistic);
        btStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btStatistic.setFocusPainted(false);
        btStatistic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btStatistic.setIconTextGap(12);
        btStatistic.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btStatisticMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btStatisticMouseExited(evt);
            }
        });
        btStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStatisticActionPerformed(evt);
            }
        });

        btTicket.setBackground(getBackground());
        btTicket.setForeground(new java.awt.Color(255, 255, 255));
        btTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-ticket-white20.png"))); // NOI18N
        btTicket.setText("Vé máy bay");
        btTicket.setBorder(null);
        grpNav.add(btTicket);
        btTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTicket.setFocusPainted(false);
        btTicket.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTicket.setIconTextGap(12);
        btTicket.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btTicketMouseExited(evt);
            }
        });
        btTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTicketActionPerformed(evt);
            }
        });

        btPromo.setBackground(getBackground());
        btPromo.setForeground(new java.awt.Color(255, 255, 255));
        btPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-promotion-white20.png"))); // NOI18N
        btPromo.setText("Khuyến mãi");
        btPromo.setBorder(null);
        grpNav.add(btPromo);
        btPromo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPromo.setFocusPainted(false);
        btPromo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPromo.setIconTextGap(12);
        btPromo.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPromoMouseExited(evt);
            }
        });
        btPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPromoActionPerformed(evt);
            }
        });

        btFlight.setBackground(getBackground());
        btFlight.setForeground(new java.awt.Color(255, 255, 255));
        btFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-flight-white20.png"))); // NOI18N
        btFlight.setText("Tuyến bay");
        btFlight.setBorder(null);
        grpNav.add(btFlight);
        btFlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFlight.setFocusPainted(false);
        btFlight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFlight.setIconTextGap(12);
        btFlight.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFlightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFlightMouseExited(evt);
            }
        });
        btFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlightActionPerformed(evt);
            }
        });

        btLogout.setBackground(getBackground());
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-logout-white20.png"))); // NOI18N
        btLogout.setText("Đăng xuất");
        btLogout.setBorder(null);
        grpNav.add(btLogout);
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogout.setFocusPainted(false);
        btLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLogout.setIconTextGap(12);
        btLogout.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLogoutMouseExited(evt);
            }
        });
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(Styles.PRI_DARK);
        jSeparator2.setForeground(Styles.PRI_DARK);

        btAirline.setBackground(getBackground());
        btAirline.setForeground(new java.awt.Color(255, 255, 255));
        btAirline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-airline-white20.png"))); // NOI18N
        btAirline.setText("Hãng bay");
        btAirline.setBorder(null);
        grpNav.add(btAirline);
        btAirline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirline.setFocusPainted(false);
        btAirline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirline.setIconTextGap(12);
        btAirline.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btAirline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAirlineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAirlineMouseExited(evt);
            }
        });
        btAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAirlineActionPerformed(evt);
            }
        });

        btAirport.setBackground(getBackground());
        btAirport.setForeground(new java.awt.Color(255, 255, 255));
        btAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-airport-white20.png"))); // NOI18N
        btAirport.setText("Sân bay");
        btAirport.setBorder(null);
        grpNav.add(btAirport);
        btAirport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAirport.setFocusPainted(false);
        btAirport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAirport.setIconTextGap(12);
        btAirport.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAirportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAirportMouseExited(evt);
            }
        });
        btAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAirportActionPerformed(evt);
            }
        });

        btAccount.setBackground(getBackground());
        btAccount.setForeground(new java.awt.Color(255, 255, 255));
        btAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-account-white20.png"))); // NOI18N
        btAccount.setText("Tài khoản");
        btAccount.setBorder(null);
        grpNav.add(btAccount);
        btAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAccount.setFocusPainted(false);
        btAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAccount.setIconTextGap(12);
        btAccount.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAccountMouseExited(evt);
            }
        });
        btAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccountActionPerformed(evt);
            }
        });

        btFeatures.setBackground(getBackground());
        btFeatures.setForeground(new java.awt.Color(255, 255, 255));
        btFeatures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/nav-features-white20.png"))); // NOI18N
        btFeatures.setText("Chức năng");
        btFeatures.setBorder(null);
        grpNav.add(btFeatures);
        btFeatures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFeatures.setFocusPainted(false);
        btFeatures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFeatures.setIconTextGap(12);
        btFeatures.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btFeatures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFeaturesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFeaturesMouseExited(evt);
            }
        });
        btFeatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFeaturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(btStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btPromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btFlight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAirport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btFeatures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        JDialog dialog = new JDialog();
        dialog.setLocationRelativeTo(this);
        int result = JOptionPane.showConfirmDialog(dialog, "Bạn có muốn đăng xuất", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            context.setVisible(false);
            try {
                SigninGUI signinGUI = new SigninGUI();
                signinGUI.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SignupEUC.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignupEUC.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SignupEUC.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btStatisticMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStatisticMouseEntered
        if (btStatistic.getBackground() == Styles.PRI_NORMAL) {
            btStatistic.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btStatisticMouseEntered

    private void btStatisticMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStatisticMouseExited
        if (btStatistic.getBackground() == Styles.PRI_DARKER) {
            btStatistic.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btStatisticMouseExited

    private void btTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTicketMouseEntered
        if (btTicket.getBackground() == Styles.PRI_NORMAL) {
            btTicket.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btTicketMouseEntered

    private void btTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTicketMouseExited
        if (btTicket.getBackground() == Styles.PRI_DARKER) {
            btTicket.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btTicketMouseExited

    private void btPromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPromoMouseEntered
        if (btPromo.getBackground() == Styles.PRI_NORMAL) {
            btPromo.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btPromoMouseEntered

    private void btPromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPromoMouseExited
        if (btPromo.getBackground() == Styles.PRI_DARKER) {
            btPromo.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btPromoMouseExited

    private void btFlightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFlightMouseEntered
        if (btFlight.getBackground() == Styles.PRI_NORMAL) {
            btFlight.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btFlightMouseEntered

    private void btFlightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFlightMouseExited
        if (btFlight.getBackground() == Styles.PRI_DARKER) {
            btFlight.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btFlightMouseExited

    private void btAirlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAirlineMouseEntered
        if (btAirline.getBackground() == Styles.PRI_NORMAL) {
            btAirline.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btAirlineMouseEntered

    private void btAirlineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAirlineMouseExited
        if (btAirline.getBackground() == Styles.PRI_DARKER) {
            btAirline.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btAirlineMouseExited

    private void btAirportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAirportMouseEntered
        if (btAirport.getBackground() == Styles.PRI_NORMAL) {
            btAirport.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btAirportMouseEntered

    private void btAirportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAirportMouseExited
        if (btAirport.getBackground() == Styles.PRI_DARKER) {
            btAirport.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btAirportMouseExited

    private void btAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseEntered
        if (btAccount.getBackground() == Styles.PRI_NORMAL) {
            btAccount.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btAccountMouseEntered

    private void btAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAccountMouseExited
        if (btAccount.getBackground() == Styles.PRI_DARKER) {
            btAccount.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btAccountMouseExited

    private void btLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseEntered
        btLogout.setBackground(Styles.PRI_DARKER);
    }//GEN-LAST:event_btLogoutMouseEntered

    private void btLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseExited
        btLogout.setBackground(Styles.PRI_NORMAL);
    }//GEN-LAST:event_btLogoutMouseExited

    private void btStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStatisticActionPerformed
        this.siteOrder = Order.STATISTIC;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btStatisticActionPerformed

    private void btTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTicketActionPerformed
        this.siteOrder = Order.TICKET;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btTicketActionPerformed

    private void btPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPromoActionPerformed
        this.siteOrder = Order.PROMOTION;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPromoActionPerformed

    private void btFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlightActionPerformed
        this.siteOrder = Order.FLIGHT;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btFlightActionPerformed

    private void btAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAirlineActionPerformed
        this.siteOrder = Order.AIRLINE;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAirlineActionPerformed

    private void btAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAirportActionPerformed
        this.siteOrder = Order.AIRPORT;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAirportActionPerformed

    private void btAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccountActionPerformed
        this.siteOrder = Order.ACCOUNT;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAccountActionPerformed

    private void btFeaturesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFeaturesMouseEntered
        if (btFeatures.getBackground() == Styles.PRI_NORMAL) {
            btFeatures.setBackground(Styles.PRI_DARKER);
        }
    }//GEN-LAST:event_btFeaturesMouseEntered

    private void btFeaturesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFeaturesMouseExited
        if (btFeatures.getBackground() == Styles.PRI_DARKER) {
            btFeatures.setBackground(Styles.PRI_NORMAL);
        }
    }//GEN-LAST:event_btFeaturesMouseExited

    private void btFeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFeaturesActionPerformed
        this.siteOrder = Order.FEATURES;
        try {
            navigateTo(siteOrder);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SidebarAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btFeaturesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btAirline;
    private javax.swing.JButton btAirport;
    private javax.swing.JButton btFeatures;
    private javax.swing.JButton btFlight;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btPromo;
    private javax.swing.JButton btStatistic;
    private javax.swing.JButton btTicket;
    private javax.swing.ButtonGroup grpNav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnHeader;
    // End of variables declaration//GEN-END:variables

}
