/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;

import assets.Site.Order;
import assets.Styles;
import javax.swing.JFrame;

/**
 *
 * @author agond
 */
public class TopbarAD extends javax.swing.JPanel {
    Order siteOrder;
    JFrame frParrent;
    /**
     * Creates new form TopbarEUC
     */
    public TopbarAD() {
        initComponents();
        style();
        siteOrder(Order.BUY_TICKET);
    }
    
    public TopbarAD(JFrame frParrent) {
        initComponents();
        style();
        siteOrder(Order.BUY_TICKET);
        this.frParrent = frParrent;
    }
    
    public void siteOrder(Order siteOrder){
        this.siteOrder = siteOrder;
        if(siteOrder == Order.BUY_TICKET){
            lbSitename.setText("Mua vé");
        } else if (siteOrder == Order.MY_TICKET) {
            lbSitename.setText("Vé của tôi");
            btCTA.setVisible(false);
        } else if (siteOrder == Order.PROMOTION) {
            lbSitename.setText("Khuyến mãi");
        } else if (siteOrder == Order.ACCOUNT) {
            lbSitename.setText("Tài khoản");
        }
    }
    
    public void style(){
        lbSitename.setForeground(Styles.PRI_DARK);
        lbSitename.setFont(Styles.H1);
        
        btCTA.setBackground(Styles.PRI_NORMAL);
        btCTA.setForeground(Styles.WHITE);
        btCTA.setFont(Styles.Body);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSitename = new javax.swing.JLabel();
        btCTA = new javax.swing.JButton();

        setBackground(Styles.WHITE);
        setPreferredSize(new java.awt.Dimension(740, 62));

        lbSitename.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbSitename.setText("Sitename");

        btCTA.setBackground(new java.awt.Color(1, 138, 165));
        btCTA.setForeground(new java.awt.Color(255, 255, 255));
        btCTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-import-white18.png"))); // NOI18N
        btCTA.setText("Import ticket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbSitename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(btCTA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSitename, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCTA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCTA;
    private javax.swing.JLabel lbSitename;
    // End of variables declaration//GEN-END:variables
}
