/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;

import DTO.entities.User;
import assets.Styles;
/**
 *
 * @author agond
 */
public class AccountAD extends javax.swing.JPanel {
    private User user;
    /**
     * Creates new form AccountAD
     */
    public AccountAD() {
        initComponents();
        styles();
    }
    
    public AccountAD(User user) {
        this.user = user;
        initComponents();
        styles();
    }
    public void styles(){
        Styles.ButtonNeutral(btAddAccount);
        Styles.ButtonSecondary(btSearchAccount);
        Styles.Table(tableAllAccounts, pnAllAccounts);
        Styles.Table(tbRolePermission, pnAllRole);        
        Styles.Table(tbAllRole, pnRolePermission);

        Styles.FormTextFeild(txtRoleName);
        Styles.ButtonDanger(btDeletePermission);
        Styles.ButtonSecondary(btUpdatePermission);
        Styles.ButtonPrimary(btAddRole);
        
        lbTitleAccounts.setFont(Styles.H2);
        lbTitleAccounts.setForeground(Styles.GRAY_600);
        lbTitleAllAccount.setFont(Styles.H2);
        lbTitleAllAccount.setForeground(Styles.GRAY_600);
        lbTitleAuth.setFont(Styles.H2);
        lbTitleAuth.setForeground(Styles.GRAY_600);
        
        lbTotalAccHead.setFont(Styles.Body);
        lbTotalAccHead.setForeground(Styles.GRAY_600);
        lbTotalAccount.setFont(Styles.Label);
        lbTotalAccount.setForeground(Styles.GRAY_600);
        lbTotalAccTail.setFont(Styles.Body);
        lbTotalAccTail.setForeground(Styles.GRAY_600);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabAccount = new javax.swing.JPanel();
        btAddAccount = new javax.swing.JButton();
        btSearchAccount = new javax.swing.JButton();
        lbTitleAccounts = new javax.swing.JLabel();
        pnAllAccounts = new javax.swing.JScrollPane();
        tableAllAccounts = new javax.swing.JTable();
        lbTotalAccHead = new javax.swing.JLabel();
        lbTotalAccount = new javax.swing.JLabel();
        lbTotalAccTail = new javax.swing.JLabel();
        tabAuth = new javax.swing.JPanel();
        pnAllAccount = new javax.swing.JPanel();
        lbTitleAllAccount = new javax.swing.JLabel();
        pnAllRole = new javax.swing.JScrollPane();
        tbAllRole = new javax.swing.JTable();
        btAddRole = new javax.swing.JButton();
        pnAuth = new javax.swing.JPanel();
        lbTitleAuth = new javax.swing.JLabel();
        txtRoleName = new javax.swing.JTextField();
        pnRolePermission = new javax.swing.JScrollPane();
        tbRolePermission = new javax.swing.JTable();
        btDeletePermission = new javax.swing.JButton();
        btUpdatePermission = new javax.swing.JButton();

        setBackground(new java.awt.Color(246, 246, 246));
        setMinimumSize(new java.awt.Dimension(740, 490));

        jTabbedPane1.setBackground(new java.awt.Color(246, 246, 246));
        jTabbedPane1.setForeground(Styles.PRI_NORMAL);

        tabAccount.setBackground(new java.awt.Color(255, 255, 255));

        btAddAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-black18.png"))); // NOI18N

        btSearchAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-search-pri18.png"))); // NOI18N
        btSearchAccount.setText("Tìm kiếm");
        btSearchAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchAccountActionPerformed(evt);
            }
        });

        lbTitleAccounts.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitleAccounts.setText("Danh sách tài khoản");

        tableAllAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Username", "Tên nhân viên", "Ngày tạo TK", "Loại TK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pnAllAccounts.setViewportView(tableAllAccounts);
        if (tableAllAccounts.getColumnModel().getColumnCount() > 0) {
            tableAllAccounts.getColumnModel().getColumn(0).setMinWidth(40);
            tableAllAccounts.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lbTotalAccHead.setFont(Styles.Micro);
        lbTotalAccHead.setText("Có tất cả");

        lbTotalAccount.setText("?");

        lbTotalAccTail.setFont(Styles.Micro);
        lbTotalAccTail.setText("tài khoản");

        javax.swing.GroupLayout tabAccountLayout = new javax.swing.GroupLayout(tabAccount);
        tabAccount.setLayout(tabAccountLayout);
        tabAccountLayout.setHorizontalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAccountLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addComponent(lbTotalAccHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalAccTail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnAllAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                            .addGroup(tabAccountLayout.createSequentialGroup()
                                .addComponent(lbTitleAccounts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSearchAccount)))
                        .addGap(24, 24, 24))))
        );
        tabAccountLayout.setVerticalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAccountLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSearchAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitleAccounts))
                .addGap(12, 12, 12)
                .addComponent(pnAllAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalAccHead)
                    .addComponent(lbTotalAccTail)
                    .addComponent(lbTotalAccount))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Tài khoản", new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-account-pri20.png")), tabAccount); // NOI18N
        tabAccount.getAccessibleContext().setAccessibleName("");

        tabAuth.setBackground(new java.awt.Color(255, 255, 255));

        pnAllAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnAllAccount.setPreferredSize(new java.awt.Dimension(217, 368));

        lbTitleAllAccount.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitleAllAccount.setText("Tất cả các loại tài khoản");

        tbAllRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Loại Tài khoản", "SL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAllRole.setMinimumSize(new java.awt.Dimension(60, 100));
        tbAllRole.setPreferredSize(new java.awt.Dimension(300, 100));
        pnAllRole.setViewportView(tbAllRole);
        if (tbAllRole.getColumnModel().getColumnCount() > 0) {
            tbAllRole.getColumnModel().getColumn(0).setMinWidth(40);
            tbAllRole.getColumnModel().getColumn(0).setMaxWidth(50);
            tbAllRole.getColumnModel().getColumn(2).setMinWidth(40);
            tbAllRole.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        btAddRole.setBackground(new java.awt.Color(27, 124, 148));
        btAddRole.setForeground(new java.awt.Color(255, 255, 255));
        btAddRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-white18.png"))); // NOI18N
        btAddRole.setText("Thêm mới");

        javax.swing.GroupLayout pnAllAccountLayout = new javax.swing.GroupLayout(pnAllAccount);
        pnAllAccount.setLayout(pnAllAccountLayout);
        pnAllAccountLayout.setHorizontalGroup(
            pnAllAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAllAccountLayout.createSequentialGroup()
                .addComponent(lbTitleAllAccount)
                .addGap(0, 84, Short.MAX_VALUE))
            .addComponent(btAddRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnAllRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnAllAccountLayout.setVerticalGroup(
            pnAllAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAllAccountLayout.createSequentialGroup()
                .addComponent(lbTitleAllAccount)
                .addGap(24, 24, 24)
                .addComponent(pnAllRole, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btAddRole, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnAuth.setBackground(new java.awt.Color(255, 255, 255));
        pnAuth.setPreferredSize(new java.awt.Dimension(455, 452));

        lbTitleAuth.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitleAuth.setText("Quyền tài khoản");

        txtRoleName.setText("Người dùng");

        tbRolePermission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Chức năng", "A", "C", "R", "U", "D"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRolePermission.setMinimumSize(new java.awt.Dimension(60, 100));
        tbRolePermission.getTableHeader().setReorderingAllowed(false);
        pnRolePermission.setViewportView(tbRolePermission);
        if (tbRolePermission.getColumnModel().getColumnCount() > 0) {
            tbRolePermission.getColumnModel().getColumn(0).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(0).setMaxWidth(50);
            tbRolePermission.getColumnModel().getColumn(2).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(2).setMaxWidth(50);
            tbRolePermission.getColumnModel().getColumn(3).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(3).setMaxWidth(50);
            tbRolePermission.getColumnModel().getColumn(4).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(4).setMaxWidth(50);
            tbRolePermission.getColumnModel().getColumn(5).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(5).setMaxWidth(50);
            tbRolePermission.getColumnModel().getColumn(6).setMinWidth(40);
            tbRolePermission.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        btDeletePermission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-delete-red18.png"))); // NOI18N
        btDeletePermission.setText("Xóa");
        btDeletePermission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletePermissionActionPerformed(evt);
            }
        });

        btUpdatePermission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-refresh-pri18.png"))); // NOI18N
        btUpdatePermission.setText("Cập nhật");

        javax.swing.GroupLayout pnAuthLayout = new javax.swing.GroupLayout(pnAuth);
        pnAuth.setLayout(pnAuthLayout);
        pnAuthLayout.setHorizontalGroup(
            pnAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAuthLayout.createSequentialGroup()
                .addComponent(lbTitleAuth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAuthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeletePermission)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUpdatePermission))
            .addComponent(pnRolePermission, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnAuthLayout.setVerticalGroup(
            pnAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAuthLayout.createSequentialGroup()
                .addGroup(pnAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitleAuth)
                    .addComponent(txtRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(pnRolePermission, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btUpdatePermission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeletePermission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout tabAuthLayout = new javax.swing.GroupLayout(tabAuth);
        tabAuth.setLayout(tabAuthLayout);
        tabAuthLayout.setHorizontalGroup(
            tabAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAuthLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnAllAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnAuth, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        tabAuthLayout.setVerticalGroup(
            tabAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAuthLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnAuth, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(pnAllAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Phân quyền", new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-pri18.png")), tabAuth); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearchAccountActionPerformed

    private void btDeletePermissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletePermissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletePermissionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAccount;
    private javax.swing.JButton btAddRole;
    private javax.swing.JButton btDeletePermission;
    private javax.swing.JButton btSearchAccount;
    private javax.swing.JButton btUpdatePermission;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbTitleAccounts;
    private javax.swing.JLabel lbTitleAllAccount;
    private javax.swing.JLabel lbTitleAuth;
    private javax.swing.JLabel lbTotalAccHead;
    private javax.swing.JLabel lbTotalAccTail;
    private javax.swing.JLabel lbTotalAccount;
    private javax.swing.JPanel pnAllAccount;
    private javax.swing.JScrollPane pnAllAccounts;
    private javax.swing.JScrollPane pnAllRole;
    private javax.swing.JPanel pnAuth;
    private javax.swing.JScrollPane pnRolePermission;
    private javax.swing.JPanel tabAccount;
    private javax.swing.JPanel tabAuth;
    private javax.swing.JTable tableAllAccounts;
    private javax.swing.JTable tbAllRole;
    private javax.swing.JTable tbRolePermission;
    private javax.swing.JTextField txtRoleName;
    // End of variables declaration//GEN-END:variables
}
