/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;
import assets.Styles;
import DTO.entities.User;
import assets.TextBubbleBorder;

/**
 *
 * @author agond
 */
public class AirportAD extends javax.swing.JPanel {
    private User user;
    /**
     * Creates new form AirportAD
     */
    public AirportAD() {
        initComponents();
        styles();
    }
    
    public AirportAD(User user) {
        this.user = user;
        initComponents();
        styles();
    }
    public  void  styles(){
        Styles.Table(tbAllAirport, pnAllAirport);
        Styles.ButtonDanger(btDeleteAirport);
        Styles.ButtonPrimary(btUpdateGate);
        Styles.ButtonSecondary(btAddAirport);
        
        lbTitle.setFont(Styles.H2);
        lbTitle.setForeground(Styles.GRAY_600);
        lbTotalAirportHead.setFont(Styles.Body);
        lbTotalAirportHead.setForeground(Styles.GRAY_600);
        lbTotalAirport.setFont(Styles.Label);
        lbTotalAirport.setForeground(Styles.GRAY_600);
        lbTotalAirportTail.setFont(Styles.Body);
        lbTotalAirportTail.setForeground(Styles.GRAY_600);
        
        TextBubbleBorder border = new TextBubbleBorder(Styles.PRI_LIGHTER, 0, 12, 0, true);
        pnAirportDetail.setBorder(border);
        
        txtAllGate.setBorder(border);
        txtAllGate.setFont(Styles.Label);
        txtAllGate.setForeground(Styles.PRI_NORMAL);
        txtAllGate.setBackground(Styles.WHITE);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        btAddAirport = new javax.swing.JButton();
        pnAllAirport = new javax.swing.JScrollPane();
        tbAllAirport = new javax.swing.JTable();
        lbTotalAirportHead = new javax.swing.JLabel();
        lbTotalAirport = new javax.swing.JLabel();
        lbTotalAirportTail = new javax.swing.JLabel();
        pnAirportDetail = new javax.swing.JPanel();
        lbAirportID = new javax.swing.JLabel();
        lbAirportName = new javax.swing.JLabel();
        lbGate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAllGate = new javax.swing.JTextArea();
        btDeleteAirport = new javax.swing.JButton();
        btUpdateGate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 450));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitle.setText("Danh sách các sân bay");

        btAddAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-pri18.png"))); // NOI18N
        btAddAirport.setText("Thêm sân bay");

        tbAllAirport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã cảng", "Tên cảng", "Tỉnh thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pnAllAirport.setViewportView(tbAllAirport);
        if (tbAllAirport.getColumnModel().getColumnCount() > 0) {
            tbAllAirport.getColumnModel().getColumn(0).setMinWidth(40);
            tbAllAirport.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lbTotalAirportHead.setFont(Styles.Micro);
        lbTotalAirportHead.setText("Có tất cả");

        lbTotalAirport.setText("64");

        lbTotalAirportTail.setFont(Styles.Micro);
        lbTotalAirportTail.setText("sân bay");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTotalAirportHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalAirport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalAirportTail)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnAllAirport, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddAirport))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle)
                    .addComponent(btAddAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(pnAllAirport, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalAirportHead)
                    .addComponent(lbTotalAirport)
                    .addComponent(lbTotalAirportTail))
                .addGap(24, 24, 24))
        );

        pnAirportDetail.setBackground(Styles.PRI_LIGHTER);

        lbAirportID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbAirportID.setForeground(Styles.GRAY_600);
        lbAirportID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAirportID.setText("HCM");

        lbAirportName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAirportName.setText("Tân Sơn Nhất");
        lbAirportName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbGate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbGate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-login-black20.png"))); // NOI18N
        lbGate.setText("Cổng");

        txtAllGate.setColumns(20);
        txtAllGate.setFont(Styles.Label);
        txtAllGate.setForeground(Styles.PRI_NORMAL);
        txtAllGate.setLineWrap(true);
        txtAllGate.setRows(5);
        txtAllGate.setText("A1, A2, A3");
        jScrollPane2.setViewportView(txtAllGate);

        btDeleteAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-delete-red18.png"))); // NOI18N
        btDeleteAirport.setText("Xóa sân bay");

        btUpdateGate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-refresh-white18.png"))); // NOI18N
        btUpdateGate.setText("Cập nhật cổng");

        javax.swing.GroupLayout pnAirportDetailLayout = new javax.swing.GroupLayout(pnAirportDetail);
        pnAirportDetail.setLayout(pnAirportDetailLayout);
        pnAirportDetailLayout.setHorizontalGroup(
            pnAirportDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAirportID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbAirportName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbGate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btDeleteAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btUpdateGate, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        pnAirportDetailLayout.setVerticalGroup(
            pnAirportDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirportDetailLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbAirportID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbGate)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2)
                .addGap(12, 12, 12)
                .addComponent(btDeleteAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btUpdateGate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(pnAirportDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(pnAirportDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAirport;
    private javax.swing.JButton btDeleteAirport;
    private javax.swing.JButton btUpdateGate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAirportID;
    private javax.swing.JLabel lbAirportName;
    private javax.swing.JLabel lbGate;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotalAirport;
    private javax.swing.JLabel lbTotalAirportHead;
    private javax.swing.JLabel lbTotalAirportTail;
    private javax.swing.JPanel pnAirportDetail;
    private javax.swing.JScrollPane pnAllAirport;
    private javax.swing.JTable tbAllAirport;
    private javax.swing.JTextArea txtAllGate;
    // End of variables declaration//GEN-END:variables
}
