/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;

import BUS.ActionBUS;
import BUS.PermissionBUS;
import DTO.entities.Action;
import DTO.entities.Person;
import DTO.entities.User;
import GUI.popup.PuFeatureAD;
import assets.Styles;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agond
 */
public class FeaturesAD extends javax.swing.JPanel {
    private Person user;
    
    private ArrayList<Action> actionList;
    private PermissionBUS permissionBUS;
    private ActionBUS actionBUS;
    private DefaultTableModel featureModel; 
    /**
     * Creates new form FeaturesAD
     */
    public FeaturesAD() {
        initComponents();
        style();
    }
    
    public FeaturesAD(User user) throws ClassNotFoundException {
        initComponents();
        this.user = user;
        try {
            this.permissionBUS = new PermissionBUS();
            this.actionBUS = new ActionBUS();
            actionList = actionBUS.getList();
            initAccessPerRole();
            initTableFeature(actionList);
        } catch (SQLException ex) {
            Logger.getLogger(FeaturesAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FeaturesAD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        style();
    }
    public void initAccessPerRole() {
        User userLogin = (User) this.user;
        if(permissionBUS.hasPerCreate(userLogin.getRoleID(), "FET")) btAddFeature.setEnabled(true);
        else btAddFeature.setEnabled(false);
        
        if(permissionBUS.hasPerDelete(userLogin.getRoleID(), "FET")) btDeleteFeature.setEnabled(true);
        else btDeleteFeature.setEnabled(false);
        
    }
    public void initTableFeature(ArrayList<Action> actions) throws ClassNotFoundException, SQLException, IOException{
        
        featureModel = (DefaultTableModel) tbAllFeature.getModel();
        featureModel.setRowCount(0);
        int stt = 1;
        String featureID, featureName, featureDesc;
        for (Action action : actionList){
            if(action.getIsDelete() == 0){
                featureID = action.getActionID();
                featureName = action.getActionName();
                featureDesc = action.getInfo();
                featureModel.addRow(new Object[]{stt++,featureID,featureName,featureDesc});
            }
        }
    }
    public void style(){
        Styles.ButtonDanger(btDeleteFeature);
        Styles.ButtonSecondary(btAddFeature);
        Styles.Table(tbAllFeature, pnAllFeature);
        
        lbTitle.setFont(Styles.H2);
        lbTitle.setForeground(Styles.GRAY_600);
        lbTotalFeatureHead.setFont(Styles.Body);
        lbTotalFeatureHead.setForeground(Styles.GRAY_600);
        lbTotalFeature.setFont(Styles.Label);
        lbTotalFeature.setForeground(Styles.GRAY_600);
        lbTotalFeatureTail.setFont(Styles.Body);
        lbTotalFeatureTail.setForeground(Styles.GRAY_600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        btAddFeature = new javax.swing.JButton();
        pnAllFeature = new javax.swing.JScrollPane();
        tbAllFeature = new javax.swing.JTable();
        lbTotalFeatureHead = new javax.swing.JLabel();
        lbTotalFeature = new javax.swing.JLabel();
        lbTotalFeatureTail = new javax.swing.JLabel();
        btDeleteFeature = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitle.setText("Các chức năng hiện có");

        btAddFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-pri18.png"))); // NOI18N
        btAddFeature.setText("Thêm chức năng");
        btAddFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAddFeatureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAddFeatureMouseExited(evt);
            }
        });
        btAddFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFeatureActionPerformed(evt);
            }
        });

        tbAllFeature.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã chức năng", "Tên chức năng", "Mô tả chức năng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAllFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAllFeatureMouseClicked(evt);
            }
        });
        pnAllFeature.setViewportView(tbAllFeature);
        if (tbAllFeature.getColumnModel().getColumnCount() > 0) {
            tbAllFeature.getColumnModel().getColumn(0).setMinWidth(46);
            tbAllFeature.getColumnModel().getColumn(0).setMaxWidth(46);
            tbAllFeature.getColumnModel().getColumn(1).setMinWidth(120);
            tbAllFeature.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        lbTotalFeatureHead.setFont(Styles.Micro);
        lbTotalFeatureHead.setText("Có tất cả");

        lbTotalFeature.setText("64");

        lbTotalFeatureTail.setFont(Styles.Micro);
        lbTotalFeatureTail.setText("chức năng");

        btDeleteFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-delete-red18.png"))); // NOI18N
        btDeleteFeature.setText("Xóa chức năng");
        btDeleteFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDeleteFeatureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDeleteFeatureMouseExited(evt);
            }
        });
        btDeleteFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteFeatureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTotalFeatureHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalFeature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalFeatureTail)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnAllFeature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDeleteFeature)
                                .addGap(18, 18, 18)
                                .addComponent(btAddFeature)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAddFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDeleteFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(pnAllFeature)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalFeatureHead)
                    .addComponent(lbTotalFeature)
                    .addComponent(lbTotalFeatureTail))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddFeatureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddFeatureMouseEntered
        btAddFeature.setBackground(Styles.PRI_NORMAL);
        btAddFeature.setForeground(Styles.WHITE);
        btAddFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-white18.png")));
    }//GEN-LAST:event_btAddFeatureMouseEntered

    private void btAddFeatureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddFeatureMouseExited
        btAddFeature.setBackground(Styles.PRI_LIGHTER);
        btAddFeature.setForeground(Styles.PRI_NORMAL);
        btAddFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-pri18.png")));
    }//GEN-LAST:event_btAddFeatureMouseExited

    private void btDeleteFeatureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteFeatureMouseEntered
        btDeleteFeature.setBackground(Styles.FUNC_DANGER);
        btDeleteFeature.setForeground(Styles.WHITE);
        btDeleteFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-delete-white18.png")));
    }//GEN-LAST:event_btDeleteFeatureMouseEntered

    private void btDeleteFeatureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteFeatureMouseExited
        btDeleteFeature.setBackground(Styles.FUNC_DANGER_LIGHT);
        btDeleteFeature.setForeground(Styles.FUNC_DANGER);
        btDeleteFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-delete-red18.png")));
    }//GEN-LAST:event_btDeleteFeatureMouseExited

    private void btAddFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFeatureActionPerformed
        PuFeatureAD puFeatureAD = new PuFeatureAD(null,(User) this.user);
        puFeatureAD.setVisible(true);
    }//GEN-LAST:event_btAddFeatureActionPerformed

    private void tbAllFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAllFeatureMouseClicked
        User userLogin = (User) this.user;
        if(evt.getClickCount() == 2 && permissionBUS.hasPerView(userLogin.getRoleID(), "FET")){
            int selectedRow = tbAllFeature.getSelectedRow();
            if(selectedRow != -1 ){
                Action action = actionList.get(selectedRow);
                if (action != null) {
                    PuFeatureAD puFeatureAD = new PuFeatureAD(action, (User) this.user);
                    puFeatureAD.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_tbAllFeatureMouseClicked

    private void btDeleteFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteFeatureActionPerformed
        int selectedRow = tbAllFeature.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Action action = actionList.get(selectedRow);
                boolean deleted = actionBUS.deleteAction(action);
                if (deleted) {
                    ActionBUS actionBUS = new ActionBUS();
                    actionList = actionBUS.getList();
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công!", "Xác nhận xóa", JOptionPane.INFORMATION_MESSAGE);
                    initTableFeature(actionList);
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AccountAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AccountAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AccountAD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btDeleteFeatureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddFeature;
    private javax.swing.JButton btDeleteFeature;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotalFeature;
    private javax.swing.JLabel lbTotalFeatureHead;
    private javax.swing.JLabel lbTotalFeatureTail;
    private javax.swing.JScrollPane pnAllFeature;
    private javax.swing.JTable tbAllFeature;
    // End of variables declaration//GEN-END:variables
}
