/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;

/**
 *
 * @author agond
 */
public class PnStatistic extends javax.swing.JPanel {

    /**
     * Creates new form PnStatistic
     */
    public PnStatistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQuickAction = new javax.swing.JLabel();
        btCreateTicket = new javax.swing.JButton();
        btCreatePromo = new javax.swing.JButton();
        btCreateFlight = new javax.swing.JButton();
        pnTicket = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbTicketTitle = new javax.swing.JLabel();
        lbTicketSubtitle = new javax.swing.JLabel();
        pnUser = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbUserTitle = new javax.swing.JLabel();
        lbUserSubtitle = new javax.swing.JLabel();
        pnAirport = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbAirportTitle = new javax.swing.JLabel();
        lbAirportSubtitle = new javax.swing.JLabel();
        pnPromo = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbPromoTitle = new javax.swing.JLabel();
        lbPromoSubtitle = new javax.swing.JLabel();
        pnAirline = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbAirlineTitle = new javax.swing.JLabel();
        lbAirlineSubtitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbQuickAction.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbQuickAction.setForeground(new java.awt.Color(84, 104, 129));
        lbQuickAction.setText("Truy cập nhanh");

        btCreateTicket.setBackground(new java.awt.Color(230, 243, 246));
        btCreateTicket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCreateTicket.setForeground(new java.awt.Color(84, 104, 129));
        btCreateTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-ticket-dark.png"))); // NOI18N
        btCreateTicket.setText("Tạo vé");
        btCreateTicket.setBorder(null);

        btCreatePromo.setBackground(new java.awt.Color(230, 243, 246));
        btCreatePromo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCreatePromo.setForeground(new java.awt.Color(84, 104, 129));
        btCreatePromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-promotion-dark.png"))); // NOI18N
        btCreatePromo.setText("Tạo chương trình KM");
        btCreatePromo.setBorder(null);

        btCreateFlight.setBackground(new java.awt.Color(230, 243, 246));
        btCreateFlight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCreateFlight.setForeground(new java.awt.Color(84, 104, 129));
        btCreateFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/png/nav-flight-dark.png"))); // NOI18N
        btCreateFlight.setText("Chuyến bay mới");
        btCreateFlight.setBorder(null);

        pnTicket.setBackground(new java.awt.Color(230, 243, 246));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/statistic-ticket.png"))); // NOI18N

        lbTicketTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTicketTitle.setForeground(new java.awt.Color(1, 104, 124));
        lbTicketTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTicketTitle.setText("0đ");

        lbTicketSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTicketSubtitle.setForeground(new java.awt.Color(84, 104, 129));
        lbTicketSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTicketSubtitle.setText("0 vé/tuần");

        javax.swing.GroupLayout pnTicketLayout = new javax.swing.GroupLayout(pnTicket);
        pnTicket.setLayout(pnTicketLayout);
        pnTicketLayout.setHorizontalGroup(
            pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTicketLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTicketSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(lbTicketTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnTicketLayout.setVerticalGroup(
            pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTicketLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTicketTitle)
                .addGap(2, 2, 2)
                .addComponent(lbTicketSubtitle)
                .addGap(12, 12, 12))
        );

        pnUser.setBackground(new java.awt.Color(230, 243, 246));
        pnUser.setPreferredSize(new java.awt.Dimension(217, 118));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/statistic-user.png"))); // NOI18N

        lbUserTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbUserTitle.setForeground(new java.awt.Color(1, 104, 124));
        lbUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbUserTitle.setText("0 new user");

        lbUserSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUserSubtitle.setForeground(new java.awt.Color(84, 104, 129));
        lbUserSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbUserSubtitle.setText("trong tuần này");

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(lbUserTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUserTitle)
                .addGap(2, 2, 2)
                .addComponent(lbUserSubtitle)
                .addGap(12, 12, 12))
        );

        pnAirport.setBackground(new java.awt.Color(230, 243, 246));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/statistic-airport.png"))); // NOI18N

        lbAirportTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbAirportTitle.setForeground(new java.awt.Color(1, 104, 124));
        lbAirportTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAirportTitle.setText("0 sân bay");

        lbAirportSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAirportSubtitle.setForeground(new java.awt.Color(84, 104, 129));
        lbAirportSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAirportSubtitle.setText("nội địa");

        javax.swing.GroupLayout pnAirportLayout = new javax.swing.GroupLayout(pnAirport);
        pnAirport.setLayout(pnAirportLayout);
        pnAirportLayout.setHorizontalGroup(
            pnAirportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirportLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAirportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAirportSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAirportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnAirportLayout.setVerticalGroup(
            pnAirportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirportLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAirportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAirportTitle)
                .addGap(2, 2, 2)
                .addComponent(lbAirportSubtitle)
                .addGap(12, 12, 12))
        );

        pnPromo.setBackground(new java.awt.Color(230, 243, 246));
        pnPromo.setPreferredSize(new java.awt.Dimension(217, 118));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/statistic-promo.png"))); // NOI18N

        lbPromoTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbPromoTitle.setForeground(new java.awt.Color(1, 104, 124));
        lbPromoTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPromoTitle.setText("0 mã giảm giá");

        lbPromoSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPromoSubtitle.setForeground(new java.awt.Color(84, 104, 129));
        lbPromoSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPromoSubtitle.setText("được thêm mới");

        javax.swing.GroupLayout pnPromoLayout = new javax.swing.GroupLayout(pnPromo);
        pnPromo.setLayout(pnPromoLayout);
        pnPromoLayout.setHorizontalGroup(
            pnPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPromoLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPromoSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPromoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnPromoLayout.setVerticalGroup(
            pnPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPromoLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPromoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPromoTitle)
                .addGap(2, 2, 2)
                .addComponent(lbPromoSubtitle)
                .addGap(12, 12, 12))
        );

        pnAirline.setBackground(new java.awt.Color(230, 243, 246));
        pnAirline.setPreferredSize(new java.awt.Dimension(217, 118));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/statistic-airline.png"))); // NOI18N

        lbAirlineTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbAirlineTitle.setForeground(new java.awt.Color(1, 104, 124));
        lbAirlineTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAirlineTitle.setText("0 hãng bay");

        lbAirlineSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAirlineSubtitle.setForeground(new java.awt.Color(84, 104, 129));
        lbAirlineSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAirlineSubtitle.setText("thường xuyên");

        javax.swing.GroupLayout pnAirlineLayout = new javax.swing.GroupLayout(pnAirline);
        pnAirline.setLayout(pnAirlineLayout);
        pnAirlineLayout.setHorizontalGroup(
            pnAirlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirlineLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAirlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAirlineSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(lbAirlineTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnAirlineLayout.setVerticalGroup(
            pnAirlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirlineLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAirlineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAirlineTitle)
                .addGap(2, 2, 2)
                .addComponent(lbAirlineSubtitle)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCreateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btCreatePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btCreateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnTicket, 216, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnUser, 216, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnAirline, 216, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbQuickAction))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnAirline, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnAirport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(lbQuickAction)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreatePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateFlight;
    private javax.swing.JButton btCreatePromo;
    private javax.swing.JButton btCreateTicket;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAirlineSubtitle;
    private javax.swing.JLabel lbAirlineTitle;
    private javax.swing.JLabel lbAirportSubtitle;
    private javax.swing.JLabel lbAirportTitle;
    private javax.swing.JLabel lbPromoSubtitle;
    private javax.swing.JLabel lbPromoTitle;
    private javax.swing.JLabel lbQuickAction;
    private javax.swing.JLabel lbTicketSubtitle;
    private javax.swing.JLabel lbTicketTitle;
    private javax.swing.JLabel lbUserSubtitle;
    private javax.swing.JLabel lbUserTitle;
    private javax.swing.JPanel pnAirline;
    private javax.swing.JPanel pnAirport;
    private javax.swing.JPanel pnPromo;
    private javax.swing.JPanel pnTicket;
    private javax.swing.JPanel pnUser;
    // End of variables declaration//GEN-END:variables
}
