/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;
import BUS.AirlineBUS;
import BUS.PermissionBUS;
import BUS.PromoBUS;
import DTO.entities.Airline;
import DTO.entities.Person;
import DTO.entities.Promotion;
import assets.Styles;
import DTO.entities.User;
import DTO.views.PromoViews;
import DTO.views.PromoViews.PromoView;
import GUI.popup.PuPromoAD;
import GUI.popup.PuPromoSearchAD;
import GUI.popup.puTicketAD;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author agond
 */
public class PromoAD extends javax.swing.JPanel {
    private Person user;
    private PermissionBUS permissionBUS;
    private AirlineBUS airlineBUS;    
    private PromoBUS promoBUS;

    
    private ArrayList<PromoView> listPromoView;
    private ArrayList<Promotion> promotions;
    private ArrayList<Airline> airlineList;    

    
    private DefaultTableModel promoModel;
    /**
     * Creates new form PromoAD
     */
    public PromoAD() {
        initComponents();
        styles();
    }
    
    public PromoAD(User user) {
        try {
            this.user = user;
            this.permissionBUS = new PermissionBUS();
            this.airlineBUS = new AirlineBUS();
            this.promoBUS = new PromoBUS();
            this.airlineList = airlineBUS.getList();
            this.promotions = promoBUS.getList();
            initComponents();
            
            styles();
            initTablePromo(promotions);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PromoAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PromoAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PromoAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void styles(){
        Styles.ButtonNeutral(btAddPromo);        
        Styles.ButtonNeutral(btExportPromo);
        Styles.ButtonNeutral(btImportPromo);
        Styles.ButtonSecondary(btSearchPromo);
        Styles.Table(tbAllPromo, pnAllPromo);
        
        lbTitle.setFont(Styles.H2);
        lbTitle.setForeground(Styles.GRAY_600);
        lbTotalPromoHead.setFont(Styles.Body);
        lbTotalPromoHead.setBackground(Styles.GRAY_600);
        lbTotalPromo.setFont(Styles.Label);
        lbTotalPromo.setBackground(Styles.GRAY_600);
        lbTotalPromoTail.setFont(Styles.Body);
        lbTotalPromoTail.setBackground(Styles.GRAY_600);
    }
    public void initAccessPerRole() {
        User userLogin = (User) this.user;
        if(permissionBUS.hasPerCreate(userLogin.getRoleID(), "PRM")) {
            btAddPromo.setEnabled(true);
            btImportPromo.setEnabled(true);
        }
        else {
            btImportPromo.setEnabled(false);
            btAddPromo.setEnabled(false);
        }
        
        
    }
    public void initTablePromo(ArrayList<Promotion> promotions) throws ClassNotFoundException, SQLException, IOException{
        initAccessPerRole();
        promoModel = (DefaultTableModel) tbAllPromo.getModel();
        promoModel.setRowCount(0);
        PromoViews promoViews = new PromoViews(promotions);
        listPromoView = promoViews.getList();
        int stt = 1;
        String promoID, airlineID, promoType;
        String dayEnd;
        for (PromoView p : listPromoView){
            if(p.HetHan == 0){
                promoID = p.MaKhuyenMai;
                airlineID = p.HangBay;
                for (Airline a : airlineList){
                    if(a.getAirlineID().equals(airlineID)){
                        airlineID = a.getAirlineName();
                        break;
                    }
                }
                dayEnd = p.NgayKetThuc;
                promoType = p.KhuyenMai;
                promoModel.addRow(new Object[]{stt++,promoID,airlineID,dayEnd,promoType});
            }
        }
        lbTotalPromo.setText(String.valueOf(promoBUS.getQuantity()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        btSearchPromo = new javax.swing.JButton();
        btAddPromo = new javax.swing.JButton();
        btImportPromo = new javax.swing.JButton();
        btExportPromo = new javax.swing.JButton();
        pnAllPromo = new javax.swing.JScrollPane();
        tbAllPromo = new javax.swing.JTable();
        lbTotalPromoHead = new javax.swing.JLabel();
        lbTotalPromo = new javax.swing.JLabel();
        lbTotalPromoTail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(740, 490));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitle.setText("Danh sách mã khuyến mãi");

        btSearchPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-search-pri18.png"))); // NOI18N
        btSearchPromo.setText("Tìm kiếm");
        btSearchPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSearchPromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSearchPromoMouseExited(evt);
            }
        });
        btSearchPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchPromoActionPerformed(evt);
            }
        });

        btAddPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-black18.png"))); // NOI18N
        btAddPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAddPromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAddPromoMouseExited(evt);
            }
        });
        btAddPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPromoActionPerformed(evt);
            }
        });

        btImportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-export-black18.png"))); // NOI18N
        btImportPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImportPromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImportPromoMouseExited(evt);
            }
        });

        btExportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-import-black18.png"))); // NOI18N
        btExportPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExportPromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExportPromoMouseExited(evt);
            }
        });

        tbAllPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khuyến mãi", "Hãng bay", "Ngày kết thúc", "Khuyến mãi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAllPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAllPromoMouseClicked(evt);
            }
        });
        pnAllPromo.setViewportView(tbAllPromo);
        if (tbAllPromo.getColumnModel().getColumnCount() > 0) {
            tbAllPromo.getColumnModel().getColumn(0).setMinWidth(40);
            tbAllPromo.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lbTotalPromoHead.setFont(Styles.Micro);
        lbTotalPromoHead.setText("Có tất cả");

        lbTotalPromo.setFont(Styles.Label);
        lbTotalPromo.setText("?");

        lbTotalPromoTail.setFont(Styles.Micro);
        lbTotalPromoTail.setText("mã khuyến mãi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTotalPromoHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalPromo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalPromoTail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnAllPromo, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExportPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btImportPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAddPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSearchPromo)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitle)
                            .addComponent(btExportPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(pnAllPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotalPromoHead)
                            .addComponent(lbTotalPromo)
                            .addComponent(lbTotalPromoTail))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImportPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearchPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(441, 441, 441))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchPromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchPromoMouseEntered
        btSearchPromo.setBackground(Styles.PRI_NORMAL);
        btSearchPromo.setForeground(Styles.WHITE);
        btSearchPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-search-white18.png")));
    }//GEN-LAST:event_btSearchPromoMouseEntered

    private void btSearchPromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchPromoMouseExited
        btSearchPromo.setBackground(Styles.PRI_LIGHTER);
        btSearchPromo.setForeground(Styles.PRI_NORMAL);
        btSearchPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-search-pri18.png")));
    }//GEN-LAST:event_btSearchPromoMouseExited

    private void btAddPromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddPromoMouseEntered
        btAddPromo.setBackground(Styles.PRI_NORMAL);
        btAddPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-white18.png")));
    }//GEN-LAST:event_btAddPromoMouseEntered

    private void btAddPromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddPromoMouseExited
        btAddPromo.setBackground(Styles.GRAY_100);
        btAddPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-add-black18.png")));
    }//GEN-LAST:event_btAddPromoMouseExited

    private void btImportPromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportPromoMouseEntered
        btImportPromo.setBackground(Styles.PRI_NORMAL);
        btImportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-import-white18.png")));
    }//GEN-LAST:event_btImportPromoMouseEntered

    private void btImportPromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportPromoMouseExited
        btImportPromo.setBackground(Styles.GRAY_100);
        btImportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-import-black18.png")));
    }//GEN-LAST:event_btImportPromoMouseExited

    private void btExportPromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExportPromoMouseEntered
        btExportPromo.setBackground(Styles.PRI_NORMAL);
        btExportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-export-white18.png")));
    }//GEN-LAST:event_btExportPromoMouseEntered

    private void btExportPromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExportPromoMouseExited
        btExportPromo.setBackground(Styles.GRAY_100);
        btExportPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-export-black18.png")));
    }//GEN-LAST:event_btExportPromoMouseExited

    private void btAddPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPromoActionPerformed
        try {
            PuPromoAD puPromoAD = new PuPromoAD((User)this.user, null);
            puPromoAD.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PromoAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAddPromoActionPerformed

    private void tbAllPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAllPromoMouseClicked
        User userLogin = (User) this.user;
        if(evt.getClickCount() == 2 && permissionBUS.hasPerView(userLogin.getRoleID(), "PRM")){
            int selectedRow = tbAllPromo.getSelectedRow();
            if(selectedRow != -1 ){
                Promotion promo = promotions.get(selectedRow);
                if (user != null) {
                    try {
                        PuPromoAD pTicketAD = new PuPromoAD((User) this.user, promo);
                        pTicketAD.setVisible(true);
                    } catch (ParseException ex) {
                        Logger.getLogger(PromoAD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tbAllPromoMouseClicked

    private void btSearchPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchPromoActionPerformed
        PuPromoSearchAD puPromoAD = new PuPromoSearchAD();
        puPromoAD.setVisible(true);
    }//GEN-LAST:event_btSearchPromoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPromo;
    private javax.swing.JButton btExportPromo;
    private javax.swing.JButton btImportPromo;
    private javax.swing.JButton btSearchPromo;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotalPromo;
    private javax.swing.JLabel lbTotalPromoHead;
    private javax.swing.JLabel lbTotalPromoTail;
    private javax.swing.JScrollPane pnAllPromo;
    private javax.swing.JTable tbAllPromo;
    // End of variables declaration//GEN-END:variables
}
