/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.body_panel;

import DTO.entities.User;
import assets.Styles;
import static assets.Styles.GRAY_200;
import assets.TextBubbleBorder;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author agond
 */
public class StatisticAD extends javax.swing.JPanel {
    private User user;
    /**
     * Creates new form StatisticAD
     */
    public StatisticAD() {
        initComponents();
        style();
    }
    
    public StatisticAD(User user) {
        this.user = user;
        initComponents();
        style();
    }
    
    public void style(){
        Styles.ButtonSecondary(btCreateTicket);
        Styles.ButtonSecondary(btCreatePromo);
        Styles.ButtonSecondary(btCreateFlight);
        lbShortcut.setFont(Styles.H2);
        lbShortcut.setForeground(Styles.GRAY_600);
        lbStatistic.setFont(Styles.H2);
        lbStatistic.setForeground(Styles.GRAY_600);
        Styles.ComboBox(cbStatisticWith);
        
        lbNewEUC.setFont(Styles.Label);
        lbNewEUC.setForeground(Styles.FUNC_WARNING);
        lbNewEUCValue.setFont(Styles.H1);
        lbNewEUCValue.setForeground(Styles.FUNC_WARNING);
        
        lbTicketCount.setFont(Styles.Label);
//        lbTicketCount.setForeground(Styles.FUNC_INFO);
        lbTicketCountValue.setFont(Styles.H1);
//        lbTicketCountValue.setForeground(Styles.FUNC_INFO);
        
        lbRevenue.setFont(Styles.Label);
        lbRevenue.setForeground(Styles.FUNC_SUCCESS);
        lbRevenueValue.setFont(Styles.H1);
        lbRevenueValue.setForeground(Styles.FUNC_SUCCESS);
        
        lbProfit.setFont(Styles.Label);
        lbProfit.setForeground(Styles.FUNC_DANGER);
        lbProfitValue.setFont(Styles.H1);
        lbProfitValue.setForeground(Styles.FUNC_DANGER);
        
        AbstractBorder border = new TextBubbleBorder(Styles.WHITE,0,20,0, false);
        pnNewEUC.setBorder(border);
        pnRevenue.setBorder(border);
        pnTicketCount.setBorder(border);
        
        lbStatisticWith.setFont(Styles.Body);
        lbStatisticWith.setForeground(Styles.GRAY_600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStatistic = new javax.swing.JLabel();
        lbStatisticWith = new javax.swing.JLabel();
        cbStatisticWith = new javax.swing.JComboBox<>();
        pnNewEUC = new javax.swing.JPanel();
        lbNewEUC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNewEUCValue = new javax.swing.JLabel();
        pnTicketCount = new javax.swing.JPanel();
        lbTicketCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTicketCountValue = new javax.swing.JLabel();
        pnRevenue = new javax.swing.JPanel();
        lbRevenue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbRevenueValue = new javax.swing.JLabel();
        lbShortcut = new javax.swing.JLabel();
        btCreateTicket = new javax.swing.JButton();
        btCreatePromo = new javax.swing.JButton();
        btCreateFlight = new javax.swing.JButton();
        pnProfit = new javax.swing.JPanel();
        lbProfit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbProfitValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbStatistic.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbStatistic.setText("Số liệu thống kê");

        lbStatisticWith.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatisticWith.setText("Thống kê theo");

        cbStatisticWith.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "Năm" }));
        cbStatisticWith.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbStatisticWith.setPreferredSize(new java.awt.Dimension(72, 28));

        pnNewEUC.setBackground(new java.awt.Color(255, 246, 214));

        lbNewEUC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNewEUC.setForeground(new java.awt.Color(255, 187, 50));
        lbNewEUC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNewEUC.setText("Khách hàng mới");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/new-user.png"))); // NOI18N

        lbNewEUCValue.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbNewEUCValue.setForeground(new java.awt.Color(255, 187, 50));
        lbNewEUCValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNewEUCValue.setText("20");
        lbNewEUCValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnNewEUCLayout = new javax.swing.GroupLayout(pnNewEUC);
        pnNewEUC.setLayout(pnNewEUCLayout);
        pnNewEUCLayout.setHorizontalGroup(
            pnNewEUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNewEUCLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnNewEUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNewEUCValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNewEUC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnNewEUCLayout.setVerticalGroup(
            pnNewEUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNewEUCLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbNewEUC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lbNewEUCValue)
                .addGap(12, 12, 12))
            .addGroup(pnNewEUCLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnTicketCount.setBackground(new java.awt.Color(216, 245, 254));

        lbTicketCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTicketCount.setForeground(new java.awt.Color(63, 164, 252));
        lbTicketCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTicketCount.setText("Số vé bán ra");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/ticket.png"))); // NOI18N

        lbTicketCountValue.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbTicketCountValue.setForeground(new java.awt.Color(63, 164, 252));
        lbTicketCountValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTicketCountValue.setText("20");
        lbTicketCountValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnTicketCountLayout = new javax.swing.GroupLayout(pnTicketCount);
        pnTicketCount.setLayout(pnTicketCountLayout);
        pnTicketCountLayout.setHorizontalGroup(
            pnTicketCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTicketCountLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnTicketCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTicketCountValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTicketCount, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnTicketCountLayout.setVerticalGroup(
            pnTicketCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTicketCountLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTicketCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lbTicketCountValue)
                .addGap(12, 12, 12))
            .addGroup(pnTicketCountLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnRevenue.setBackground(new java.awt.Color(228, 252, 214));

        lbRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbRevenue.setForeground(new java.awt.Color(55, 196, 51));
        lbRevenue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRevenue.setText("Doanh số");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/revenue.png"))); // NOI18N

        lbRevenueValue.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbRevenueValue.setForeground(new java.awt.Color(55, 196, 51));
        lbRevenueValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRevenueValue.setText("20.000.000");
        lbRevenueValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnRevenueLayout = new javax.swing.GroupLayout(pnRevenue);
        pnRevenue.setLayout(pnRevenueLayout);
        pnRevenueLayout.setHorizontalGroup(
            pnRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRevenueLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbRevenueValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnRevenueLayout.setVerticalGroup(
            pnRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRevenueLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbRevenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lbRevenueValue)
                .addGap(12, 12, 12))
            .addGroup(pnRevenueLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbShortcut.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbShortcut.setText("Truy cập nhanh");

        btCreateTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-ticket-pri18.png"))); // NOI18N
        btCreateTicket.setText("Tạo vé");

        btCreatePromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-promotion-pri18.png"))); // NOI18N
        btCreatePromo.setText("Tạo chương trình KM");

        btCreateFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-flight-pri18.png"))); // NOI18N
        btCreateFlight.setText("Thêm chuyến bay mới");

        pnProfit.setBackground(new java.awt.Color(255, 229, 211));

        lbProfit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbProfit.setForeground(new java.awt.Color(255, 58, 40));
        lbProfit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProfit.setText("Lợi nhuận");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/profit.png"))); // NOI18N

        lbProfitValue.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbProfitValue.setForeground(new java.awt.Color(255, 58, 40));
        lbProfitValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProfitValue.setText("20.000.000");
        lbProfitValue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnProfitLayout = new javax.swing.GroupLayout(pnProfit);
        pnProfit.setLayout(pnProfitLayout);
        pnProfitLayout.setHorizontalGroup(
            pnProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProfitLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbProfitValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbProfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pnProfitLayout.setVerticalGroup(
            pnProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfitLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbProfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lbProfitValue)
                .addGap(12, 12, 12))
            .addGroup(pnProfitLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbStatistic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbStatisticWith)
                        .addGap(12, 12, 12)
                        .addComponent(cbStatisticWith, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbShortcut)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnNewEUC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCreateTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnProfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCreatePromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnTicketCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCreateFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbStatisticWith)
                        .addComponent(cbStatisticWith, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbStatistic))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnNewEUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnTicketCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(pnProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbShortcut)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreatePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateFlight;
    private javax.swing.JButton btCreatePromo;
    private javax.swing.JButton btCreateTicket;
    private javax.swing.JComboBox<String> cbStatisticWith;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbNewEUC;
    private javax.swing.JLabel lbNewEUCValue;
    private javax.swing.JLabel lbProfit;
    private javax.swing.JLabel lbProfitValue;
    private javax.swing.JLabel lbRevenue;
    private javax.swing.JLabel lbRevenueValue;
    private javax.swing.JLabel lbShortcut;
    private javax.swing.JLabel lbStatistic;
    private javax.swing.JLabel lbStatisticWith;
    private javax.swing.JLabel lbTicketCount;
    private javax.swing.JLabel lbTicketCountValue;
    private javax.swing.JPanel pnNewEUC;
    private javax.swing.JPanel pnProfit;
    private javax.swing.JPanel pnRevenue;
    private javax.swing.JPanel pnTicketCount;
    // End of variables declaration//GEN-END:variables
}
