/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.popup;

import BUS.AirlineBUS;
import DAO.AirlineDAO;
import DTO.entities.Airline;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class PuAirline extends javax.swing.JFrame {
    private AirlineBUS airlineBUS;
    /**
     * Creates new form PuAirplane
     */
    public PuAirline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAirlineInfo = new javax.swing.JPanel();
        lbAirlineName = new javax.swing.JLabel();
        PopupHeader = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        txtAirlineName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnAirlineInfo.setBackground(new java.awt.Color(255, 255, 255));

        lbAirlineName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbAirlineName.setText("Tên Hãng Bay");

        PopupHeader.setBackground(new java.awt.Color(1, 138, 165));

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-airline-white32.png"))); // NOI18N
        lbHeader.setText("Hãng bay");

        javax.swing.GroupLayout PopupHeaderLayout = new javax.swing.GroupLayout(PopupHeader);
        PopupHeader.setLayout(PopupHeaderLayout);
        PopupHeaderLayout.setHorizontalGroup(
            PopupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupHeaderLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(lbHeader)
                .addGap(128, 128, 128))
        );
        PopupHeaderLayout.setVerticalGroup(
            PopupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHeader)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btSave.setBackground(new java.awt.Color(1, 138, 165));
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-save-white18.png"))); // NOI18N
        btSave.setText("Lưu thông tin");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        txtAirlineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAirlineInfoLayout = new javax.swing.GroupLayout(pnAirlineInfo);
        pnAirlineInfo.setLayout(pnAirlineInfoLayout);
        pnAirlineInfoLayout.setHorizontalGroup(
            pnAirlineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirlineInfoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbAirlineName)
                .addGap(39, 39, 39)
                .addComponent(txtAirlineName)
                .addGap(28, 28, 28))
            .addComponent(PopupHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnAirlineInfoLayout.setVerticalGroup(
            pnAirlineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirlineInfoLayout.createSequentialGroup()
                .addComponent(PopupHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnAirlineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAirlineName)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAirlineInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAirlineInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
    String airlineName = txtAirlineName.getText().trim();
    String modifiedAirlineName = airlineName + " Airlines";
    if (!airlineName.isEmpty()) {
        String[] words = modifiedAirlineName.split(" ");
        StringBuilder airlineIDBuilder = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                airlineIDBuilder.append(Character.toUpperCase(word.charAt(0)));
            }
        }
        String airlineID = airlineIDBuilder.toString();
        
 // Thêm "Airline" vào tên hãng bay
        
        Airline airline = new Airline();
        airline.setAirlineID(airlineID);
        airline.setAirlineName(modifiedAirlineName);
        airline.setIsDelete(0); 
        try {
            airlineBUS = new AirlineBUS();
            boolean success = airlineBUS.create(airline);
            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm hãng bay thành công");
                setVisible(false);            
            } else {
                JOptionPane.showMessageDialog(this, "Thêm hãng bay thất bại");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            // Xử lý ngoại lệ nếu có lỗi khi kết nối cơ sở dữ liệu.
        } catch (IOException ex) {
            // Xử lý ngoại lệ nếu có lỗi khi đọc tệp cấu hình. 
        }
    }else {
        JOptionPane.showMessageDialog(this, "Không được để trống tên hãng bay");
    }
    }//GEN-LAST:event_btSaveActionPerformed

    private void txtAirlineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuAirline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuAirline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuAirline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuAirline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuAirline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PopupHeader;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbAirlineName;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JPanel pnAirlineInfo;
    private javax.swing.JTextField txtAirlineName;
    // End of variables declaration//GEN-END:variables
}
