
package GUI.popup;
import BUS.AirportBUS;
import DAO.AirportDAO;
import DTO.entities.Airport;
import DTO.views.AirportViews;
import GUI.body_panel.AirportAD;
import assets.Styles;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class PuAirportAD extends javax.swing.JFrame {
    private AirportAD airportAD;
    private ArrayList<Airport> listAirport;
    private ArrayList<AirportViews.AirportView> listAirportView;
    private AirportBUS airportBUS;
    ArrayList<String> provinces = new ArrayList<>();
    DefaultComboBoxModel<String> provinceModel = new DefaultComboBoxModel<>(provinces.toArray(new String[0]));
    public PuAirportAD() {
        initComponents();
        styles();
    }
    public PuAirportAD(JFrame parent) {
        setLocationRelativeTo(parent); // Hiển thị dialog ở giữa cửa sổ gốc
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        initComponents();
        styles();
    }
    public void styles() {
        this.getContentPane().setBackground(Styles.WHITE);
        Styles.FormLabel(lbAirportName);
        Styles.FormTextFeild(txtAirportName);
        Styles.FormLabel(lbAirportID);
        Styles.FormTextFeild(txtAirportID);        
        Styles.ComboBox(cbAirportProvince);
        Styles.FormLabel(lbProvince);
        Styles.ButtonPrimary(btSave);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAirportInfo = new javax.swing.JPanel();
        lbAirportName = new javax.swing.JLabel();
        cbAirportProvince = new javax.swing.JComboBox<>();
        lbProvince = new javax.swing.JLabel();
        lbAirportID = new javax.swing.JLabel();
        PopupHeader = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        txtAirportName = new javax.swing.JTextField();
        txtAirportID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnAirportInfo.setBackground(new java.awt.Color(255, 255, 255));

        lbAirportName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbAirportName.setText("Tên Cảng");

        cbAirportProvince.setBackground(new java.awt.Color(240, 240, 240));
        cbAirportProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "An Giang", "Bà Rịa-Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Tĩnh", "Hải Dương", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái", "Phú Yên", "Cần Thơ", "Đà Nẵng", "Hải Phòng", "Hà Nội", "TP HCM" }));
        cbAirportProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirportProvinceActionPerformed(evt);
            }
        });

        lbProvince.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbProvince.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbProvince.setText("Tỉnh thành");

        lbAirportID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbAirportID.setText("Mã Cảng");

        PopupHeader.setBackground(new java.awt.Color(1, 138, 165));

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/info-airport-white32.png"))); // NOI18N
        lbHeader.setText("Cảng hàng không");

        javax.swing.GroupLayout PopupHeaderLayout = new javax.swing.GroupLayout(PopupHeader);
        PopupHeader.setLayout(PopupHeaderLayout);
        PopupHeaderLayout.setHorizontalGroup(
            PopupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopupHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHeader)
                .addGap(76, 76, 76))
        );
        PopupHeaderLayout.setVerticalGroup(
            PopupHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHeader)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btSave.setBackground(new java.awt.Color(1, 138, 165));
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-save-white18.png"))); // NOI18N
        btSave.setText("Lưu cảng hàng thông");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        txtAirportName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirportNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnAirportInfoLayout = new javax.swing.GroupLayout(pnAirportInfo);
        pnAirportInfo.setLayout(pnAirportInfoLayout);
        pnAirportInfoLayout.setHorizontalGroup(
            pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirportInfoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAirportName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAirportID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbProvince, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAirportInfoLayout.createSequentialGroup()
                        .addComponent(cbAirportProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(txtAirportName)
                    .addComponent(txtAirportID))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAirportInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PopupHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnAirportInfoLayout.setVerticalGroup(
            pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAirportInfoLayout.createSequentialGroup()
                .addComponent(PopupHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAirportName)
                    .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAirportID)
                    .addComponent(txtAirportID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnAirportInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProvince)
                    .addComponent(cbAirportProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PopupHeader.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAirportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnAirportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnAirportInfo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isValidAirportID(String airportID) {
    // Kiểm tra định dạng ID sân bay
        return airportID.matches("^[A-Z]{3}$");
    }

    private boolean isDuplicateAirportID(String airportID) {
//     if (AirportDAO.existsAirportID(airportID)) {
//         return true;
//     } else {
//         return false;
//     }
        return false; // Giả sử không có sự trùng lặp
}
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        String airportID = txtAirportID.getText().trim();
        String airportName = txtAirportName.getText().trim();
        String province = cbAirportProvince.getSelectedItem().toString().trim();

        // Kiểm tra định dạng ID sân bay
        if (!isValidAirportID(airportID)) {
        JOptionPane.showMessageDialog(null, "ID sân bay không hợp lệ. Vui lòng nhập 3 chữ cái viết hoa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

        try {
            airportBUS = new AirportBUS();
            if (airportBUS.existsAirportID(airportID)) {
                JOptionPane.showMessageDialog(null, "ID sân bay đã tồn tại. Vui lòng chọn ID khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Airport airport = new Airport();
            airport.setAirportID(airportID);
            airport.setAirportName(airportName);
            airport.setProvince(province);
            airport.setIsDelete(0);

            boolean success = airportBUS.create(airport);

            if (success) {
                JOptionPane.showMessageDialog(null, "Thêm sân bay thành công: " + airportID);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm sân bay thất bại: " + airportID, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi thực hiện thêm sân bay.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSaveActionPerformed

//    private void refreshAirportList() throws IOException {
//    try {
//        // Tạo đối tượng AirportDAO
//        AirportDAO airportDAO = new AirportDAO();
//
//        // Gọi phương thức đọc lại danh sách sân bay từ đối tượng AirportDAO
//        ArrayList<Airport> airportList = airportDAO.getList();
//
//        // Cập nhật danh sách sân bay trong giao diện người dùng
//        DefaultTableModel model = (DefaultTableModel) tbAllAirport.getModel();
//        model.setRowCount(0); // Xóa các hàng hiện tại trong bảng
//
//        for (int i = 0; i < airportList.size(); i++) {
//            Airport airport = airportList.get(i);
//            Object[] rowData = { i+1, airport.getAirportID(), airport.getAirportName(), airport.getProvince() };
//            model.addRow(rowData); // Thêm hàng mới vào bảng
//        }
//    } catch (ClassNotFoundException | SQLException ex) {
//        // Xử lý lỗi nếu có
//        ex.printStackTrace();
//    }
//}
    private void cbAirportProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirportProvinceActionPerformed

    }//GEN-LAST:event_cbAirportProvinceActionPerformed

    private void txtAirportNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirportNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirportNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuAirportAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuAirportAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuAirportAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuAirportAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuAirportAD().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PopupHeader;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbAirportProvince;
    private javax.swing.JLabel lbAirportID;
    private javax.swing.JLabel lbAirportName;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbProvince;
    private javax.swing.JPanel pnAirportInfo;
    private javax.swing.JTextField txtAirportID;
    private javax.swing.JTextField txtAirportName;
    // End of variables declaration//GEN-END:variables
}
