/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.popup;
import BUS.ActionBUS;
import BUS.PermissionBUS;
import DTO.entities.Action;
import DTO.entities.User;
import GUI.body_panel.FeaturesAD;
import assets.EnumCheck;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import assets.Styles;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author WIN 10
 */
public class PuFeatureAD extends javax.swing.JFrame {
    private Action action;
    private User user;
    private PermissionBUS permissionBUS;
    private ActionBUS actionBUS;
    /**
     * Creates new form PuFeatureAD
     */
    public PuFeatureAD(Action action, User user) {
        try {
            this.action = action;
            System.out.println(action);
            this.user = user;
            this.permissionBUS = new PermissionBUS();
            this.actionBUS = new ActionBUS();
            initComponents();
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/image/app-favicon.png")));
            this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            this.setLocationRelativeTo(null);
            this.setTitle("Tài khoản");
            style();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void style(){
        Styles.ButtonPrimary(btnSaveFeature);
        Styles.FormLabel(jLabel1);        
        Styles.FormLabel(jLabel2);
        Styles.FormLabel(jLabel3);
        Styles.FormTextFeild(txtFeatureID);        
        Styles.FormTextFeild(txtFeatureName);
    }
    public void init(){
        if(action != null){
            txtFeatureID.setText(this.action.getActionID());
            txtFeatureName.setText(this.action.getActionName());
            txtFeatureDesc.setText(this.action.getInfo());
            if(permissionBUS.hasPerView(this.user.getRoleID(), "FET")){
                btnSaveFeature.setEnabled(true);
            }else btnSaveFeature.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupHeader1 = new GUI.components.PopupHeader("Chức năng", "/assets/icon/nav-features-white20");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFeatureID = new javax.swing.JTextField();
        txtFeatureName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFeatureDesc = new javax.swing.JTextArea();
        btnSaveFeature = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Styles.WHITE);
        setPreferredSize(new java.awt.Dimension(360, 350));

        jLabel1.setText("Mã chức năng");

        jLabel2.setText("Tên chức năng");

        jLabel3.setText("Mô tả chức năng");

        txtFeatureID.setMinimumSize(new java.awt.Dimension(120, 22));

        txtFeatureDesc.setColumns(20);
        txtFeatureDesc.setRows(5);
        txtFeatureDesc.setMinimumSize(new java.awt.Dimension(30, 20));
        jScrollPane1.setViewportView(txtFeatureDesc);

        btnSaveFeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/action-save-white18.png"))); // NOI18N
        btnSaveFeature.setText("Lưu thông tin");
        btnSaveFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFeatureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveFeature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFeatureName)
                            .addComponent(txtFeatureID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(popupHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFeatureID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFeatureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFeatureActionPerformed
        String featureID = txtFeatureID.getText().trim();        
        String featureName = txtFeatureName.getText().trim();
        String featureDecs = txtFeatureDesc.getText().trim();
        String strNoti = "";
        if(featureID.equals("")){
            strNoti = "ID không được để trống";
            JOptionPane.showMessageDialog(this,strNoti, "Thông báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        if(featureName.equals("")){
            strNoti = "Tên chức năng không được để trống";
            JOptionPane.showMessageDialog(this,strNoti, "Thông báo lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
        Action action = new Action();
        action.setActionID(featureID);
        action.setActionName(featureName);
        action.setInfo(featureDecs);
        action.setIsDelete(0);
        if(this.action == null){
            try {
                boolean check = actionBUS.createNewAction(action);
                if(check) { 
                    JOptionPane.showMessageDialog(this,"Đã thêm mới tính năng thành công", "Tạo thành công", JOptionPane.INFORMATION_MESSAGE);
                    FeaturesAD featuresAD = new FeaturesAD(this.user);
                    this.setVisible(false);
                    featuresAD.setVisible(true);
                    ActionBUS actionBUS = new ActionBUS();
                    featuresAD.initTableFeature(actionBUS.getList());
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                boolean check = actionBUS.updateAction(action);
                if(check){
                    JOptionPane.showMessageDialog(this,"Đã cập nhật thành công", "Cập nhật thành công", JOptionPane.INFORMATION_MESSAGE);
                    FeaturesAD featuresAD = new FeaturesAD(this.user);
                    this.setVisible(false);
                    featuresAD.setVisible(true);
                    ActionBUS actionBUS = new ActionBUS();
                    featuresAD.initTableFeature(actionBUS.getList());
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PuFeatureAD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveFeatureActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveFeature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.components.PopupHeader popupHeader1;
    private javax.swing.JTextArea txtFeatureDesc;
    private javax.swing.JTextField txtFeatureID;
    private javax.swing.JTextField txtFeatureName;
    // End of variables declaration//GEN-END:variables
}
